---
title: 'New approach to time-variable inputs'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
---

# Overview
Objective is to demonstrate new approach for variable inputs.

# Prep

```{r}
devtools::load_all()
```

# Parameters

```{r}
grp_pars <- list(grps = c('m0', 'm1', 'm2','sr1'),
                 yield = c(all = 0.05),
                 xa_fresh = c(all = 1),
                 xa_init = c(all = 0.5),
                 dd_rate = c(all = 0.1),
                 ks = c(default = 1.153337, sr1 = 0.461335),
                 qhat_opt = c(m0 = 1, m1 = 1, m2 = 2, sr1 = 8.95),
                 T_opt = c(m0 = 18, m1 = 18, m2 = 28, sr1 = 43.75),
                 T_min = c(m0 = 0, m1 = 6.41, m2 = 6.41, sr1 = 0),
                 T_max = c(m0 = 25, m1 = 25, m2 = 38, sr1 = 51.25))

mic_pars <- list(ks_SO4 = 0.00694, 
                 km_urea = 0.913)

sub_pars <- list(subs = c('VSd'),
                 T_opt_hyd = c(VSd = 60),
                 T_min_hyd = c(all = 0),
                 T_max_hyd = c(all = 90),
                 hydrol_opt = c(VSd = 0.1),
                 sub_fresh = c(VSd = 50),
                 sub_init = c(VSd = 0))

man_pars <- list(conc_fresh = c(VFA = 0), 
                  pH = 7, dens = 1000)

```

Slurry mass data.

```{r}
var_dat <- data.frame(time = c(0, 1, 10, 15, 30), 
                      slurry_mass = c(1000, 7000, 2000, 1500, 3000),
                      temp_C = c(10, 15, 15, 20, 20))
plot(slurry_mass ~ time, data = var_dat, type = 'o')
plot(temp_C ~ time, data = var_dat, type = 'o')
```

```{r}
var_pars <- list(var = var_dat)
```

# 0. Variable slurry mass and temp_C

```{r}
devtools::load_all()
out0 <- abm(50, var_pars = var_pars)
```

```{r}
plot(CH4_emis_rate ~ time, data = out0, type = 'l')
plot(temp_C ~ time, data = out0, type = 'l')
```

# 1. Variable sub_fresh

```{r}
var_dat <- data.frame(time = c(0, 1, 10, 15, 30, 50), 
                      slurry_mass = c(1000, 7000, 2000, 5000, 3000, 10000),
                      temp_C = c(10, 15, 15, 20, 20, 5))
var_dat
```



```{r}
var_dat
var_dat$sub_fresh <- rep(list(c(VSd = 50)), nrow(var_dat))
var_dat$sub_fresh[3] <- list(c(VSd = 100))
var_dat$sub_fresh[4] <- list(c(VSd = 10))
var_dat$sub_fresh[5] <- list(c(VSd = 0))
var_dat
var_dat[1, 4]
var_dat[5, 4]
```

```{r}
devtools::load_all()
out1 <- abm(50, var_pars = list(var = var_dat))
```

```{r}
plot(CH4_emis_rate ~ time, data = out1, type = 'l')
plot(temp_C ~ time, data = out1, type = 'l')
plot(VSd_conc ~ time, data = out1, type = 'l')
lines(VSd_conc ~ time, data = out0, col = 'red')
```

# 2. More variable inputs

```{r}
var_dat <- data.frame(time = c(0, 1, 10, 15, 30, 50), 
                      slurry_mass = c(1000, 7000, 2000, 5000, 3000, 10000),
                      temp_C = 30)
var_dat
```

VSd.

```{r}
var_dat$sub_fresh <- rep(list(c(VSd = 50)), nrow(var_dat))
var_dat$sub_fresh[3] <- list(c(VSd = 100))
```

Some microbial parameters for a shift in temperature optima, "adaptation" for example.

```{r}
grp_pars
for (i in 1:nrow(var_dat)) {
  var_dat$T_opt[i] <- list(grp_pars$T_opt)
}
var_dat
```


```{r}
devtools::load_all()
out2 <- abm(50, var_pars = list(var = var_dat))
```

```{r}
plot(CH4_emis_rate ~ time, data = out2, type = 'l')
lines(CH4_emis_rate ~ time, data = out1, col = 'red')
plot(temp_C ~ time, data = out1, type = 'l')
plot(VSd_conc ~ time, data = out1, type = 'l')
lines(VSd_conc ~ time, data = out0, col = 'red')
```


