---
title: 'Representative dmo for HYPUD'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y %H:%M')`"
---

# Overview
This demo compares regular and high-frequency slurry removal from pig barns, plus storage emission.

# Prep

```{r}
devtools::load_all()
library(data.table)
library(ggplot2)
```

# Inputs
Say, 450 pigs, constant slurry production at 5 kg/pig-d, over 11 week batch.

```{r}
mng_pars1 <- list(slurry_prod_rate = 2200, 
                  slurry_mass = 20000,     
                  storage_depth = 2,     
                  resid_depth = 0.1,      
                  area = 200,              
                  empty_int = 73,          
                  temp_C = 18, 
                  wash_water = 0,            
                  wash_int = NA,
                  rest_d = 0,
                  resid_enrich = 0.5)
```

```{r}
sub_pars <- list(subs = c('VSd'),
                 T_opt_hyd = c(VSd = 40),
                 T_min_hyd = c(VSd = 0),
                 T_max_hyd = c(VSd = 90),
                 hydrol_opt = c(VSd = 0.008),
                 sub_fresh = c(VSd = 50),
                 sub_init = c(VSd = 50))
```

```{r}
grp_pars <- list(grps = c('m0', 'm1', 'm2','sr1'),
                 yield = c(default = 0.05, sr1 = 0.065),
                 xa_fresh = c(all = 0.05),
                 xa_init = c(all = 0.05),
                 dd_rate = c(all = 0.02),
                 ks = c(default = 1, sr1 = 0.5),
                 qhat_opt = c(m0 = 0.8, m1 = 0.9, m2 = 1.5, sr1 = 9),
                 T_opt = c(m0 = 12, m1 = 18, m2 = 28, sr1 = 44),
                 T_min = c(m0 = 0, m1 = 6.41, m2 = 6.41, sr1 = 0),
                 T_max = c(m0 = 25, m1 = 25, m2 = 38, sr1 = 51))
```

```{r}
mic_pars <- list(dd_rate_xa = 0.02)
```

```{r}
man_pars <- list(VFA_fresh = c(VFA = 2), pH = 7, dens = 1000)

chem_pars <- list(COD_conv = c(CH4 = 1/0.2507, xa = 1/0.7069561,
                               VFA = 1/0.9383125, S = 1/0.5015, VS = 1/0.69, 
                               CO2_aer = 1/0.436, CO2_sr = 1/1.2, 
                               C_xa = 1/0.3753125))
```

```{r}
out1b <- abm(365.1,
             mng_pars = mng_pars1,
             man_pars = man_pars,
             grp_pars = grp_pars,
             mic_pars = mic_pars,
             sub_pars = sub_pars,
             chem_pars = chem_pars,
             startup = 1)
```


```{r}
setDT(out1b)
plot(CH4_emis_rate ~ time, data = out1b) 
plot(1000 * CH4_emis_cum / (slurry_load * VSd_conc) ~ time, data = out1b) 
plot(VSd_conc ~ time, data = out1b) 
plot(VFA_conc ~ time, data = out1b, type = 'l') 
plot(m0_conc ~ time, data = out1b, type = 'l') 
plot(m1_conc ~ time, data = out1b, type = 'l') 
plot(m2_conc ~ time, data = out1b, type = 'l') 
plot(CH4_emis_cum / 400 / time ~ time, data = out1b, 
     type = 'l', ylim = c(0, 20), 
     xlab = 'Time (d)', ylab = expression('Ave. CH'[4]~'emission rate'~(g~'pig'^'-1'~d^'-1')))
par(new = TRUE)
plot(CH4_emis_rate ~ time, data = out1b, type = 'l', lty = 2, col = 'gray46', 
     ylim = c(0, 13000), axes = F, xlab = '', ylab = '')
```

Now storage of removed slurry.

```{r}
out1b <- out1b[c(!duplicated(time[-1]), TRUE), ]
slurry_mass_dat <- data.table(time = out1b$time, slurry_mass = out1b$slurry_mass_eff)
sub_dat <- data.table(time = out1b$time, VSd = out1b$VSd_conc)
VFA_dat <- data.table(time = out1b$time, VFA = out1b$VFA_conc)
```

```{r}
devtools::load_all()
out1e <- abm(365,
             mng_pars = mng_pars1,
             man_pars = man_pars,
             grp_pars = grp_pars,
             mic_pars = mic_pars,
             sub_pars = sub_pars,
             chem_pars = chem_pars,
             var_pars = list(var = slurry_mass_dat, sub_fresh = sub_dat, VFA_fresh = VFA_dat))
```

```{r}
setDT(out1e)
plot(1000 * CH4_emis_cum / (slurry_load * VSd_conc) ~ time, data = out1e) 
plot(CH4_emis_cum / 400 / time ~ time, data = out1e, 
     type = 'l', ylim = c(0, 50), 
     xlab = 'Time (d)', ylab = expression('Ave. CH'[4]~'emission rate'~(g~'pig'^'-1'~d^'-1')))
par(new = TRUE)
plot(CH4_emis_rate ~ time, data = out1e, type = 'l', lty = 2, col = 'gray46', 
     ylim = c(0, 200000), axes = F, xlab = '', ylab = '')
plot(VSd_conc ~ time, data = out1e) 
plot(VFA_conc ~ time, data = out1e) 
```

```{r}
plot(VFA_conc ~ time, data = out1e, type = 'l')
```

Scenario 2 is with frequent emptying.


```{r}
mng_pars2 <- list(slurry_prod_rate = 2200, 
                  slurry_mass = 2000,     
                  storage_depth = 2,     
                  resid_depth = 0.01,      
                  area = 200,              
                  empty_int = 1,          
                  temp_C = 18, 
                  wash_water = 0,            
                  wash_int = NA,
                  rest_d = 0,
                  resid_enrich = 0.5)
```


```{r}
out2b <- abm(365,
             mng_pars = mng_pars2,
             man_pars = man_pars,
             grp_pars = grp_pars,
             mic_pars = mic_pars,
             sub_pars = sub_pars,
             chem_pars = chem_pars,
             startup = 1)
```


```{r}
setDT(out2b)
plot(VFA_conc ~ time, data = out2b, type = 'l') 
plot(slurry_mass ~ time, data = out2b, type = 'l') 
plot(CH4_emis_cum / 400 / time ~ time, data = out2b, 
     type = 'l', ylim = c(0, 20), 
     xlab = 'Time (d)', ylab = expression('Ave. CH'[4]~'emission'~(g~'pig'^'-1'~d^'-1')))
abline(h = 0, lty = 1)
```

Now storage of slurry removed from the barn.

```{r}
out2b <- out2b[c(!duplicated(time[-1]), TRUE), ]
slurry_mass_dat <- data.table(time = out2b$time, slurry_mass = out2b$slurry_mass_eff)
sub_dat <- data.table(time = out2b$time, VSd = out2b$VSd_eff_conc)
VFA_dat <- data.table(time = out2b$time, VFA = out2b$VFA_eff_conc)
```

```{r}
out2e <- abm(365,
             mng_pars = mng_pars2,
             man_pars = man_pars,
             grp_pars = grp_pars,
             mic_pars = mic_pars,
             sub_pars = sub_pars,
             chem_pars = chem_pars,
             var_pars = list(var = slurry_mass_dat, sub_fresh = sub_dat, VFA_fresh = VFA_dat))
```

```{r}
setDT(out2e)
plot(CH4_emis_cum / 400 / time ~ time, data = out2e, 
     type = 'l', ylim = c(0, 50), 
     xlab = 'Time (d)', ylab = expression('Ave. CH'[4]~'emission'~(g~'pig'^'-1'~d^'-1')))
par(new = TRUE)
plot(CH4_emis_rate ~ time, data = out2e, type = 'l', lty = 2, col = 'gray46', 
     ylim = c(0, 300000), axes = F, xlab = '', ylab = '')

plot(CH4_emis_rate / (slurry_mass / 1000) ~ time, data = out2e)
```




