# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arrh_func_cpp <- function(A, E, R, temp_K) {
    .Call('_ABM_Arrh_func_cpp', PACKAGE = 'ABM', A, E, R, temp_K)
}

CTM_cpp <- function(tt, top, tmin, tmax, yopt) {
    .Call('_ABM_CTM_cpp', PACKAGE = 'ABM', tt, top, tmin, tmax, yopt)
}

grepl_cpp <- function(pattern, x) {
    .Call('_ABM_grepl_cpp', PACKAGE = 'ABM', pattern, x)
}

computeInhibition_cpp <- function(pH_inhib_overrule, pH, NH3_frac, HAC_frac, H2S_frac, TAN, VFA, sulfide, slurry_mass, pH_LL, pH_UL, ki_NH3_min, ki_NH3_max, ki_NH4_min, ki_NH4_max, ki_HAC, ki_H2S_slope, ki_H2S_int, IC50_low) {
    .Call('_ABM_computeInhibition_cpp', PACKAGE = 'ABM', pH_inhib_overrule, pH, NH3_frac, HAC_frac, H2S_frac, TAN, VFA, sulfide, slurry_mass, pH_LL, pH_UL, ki_NH3_min, ki_NH3_max, ki_NH4_min, ki_NH4_max, ki_HAC, ki_H2S_slope, ki_H2S_int, IC50_low)
}

