# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Arrh_func_cpp <- function(A, E, R, temp_K, scale_alpha_opt, alpha_opt_scale_type, alpha_opt_scale_CP) {
    .Call('_ABM_Arrh_func_cpp', PACKAGE = 'ABM', A, E, R, temp_K, scale_alpha_opt, alpha_opt_scale_type, alpha_opt_scale_CP)
}

CTM_cpp <- function(tt, top, tmin, tmax, yopt) {
    .Call('_ABM_CTM_cpp', PACKAGE = 'ABM', tt, top, tmin, tmax, yopt)
}

call_int <- function(temp_C_fun, x) {
    .Call('_ABM_call_int', PACKAGE = 'ABM', temp_C_fun, x)
}

extract_xa_cpp <- function(y, n_mic) {
    .Call('_ABM_extract_xa_cpp', PACKAGE = 'ABM', y, n_mic)
}

rates_cpp <- function(t, y, parms) {
    .Call('_ABM_rates_cpp', PACKAGE = 'ABM', t, y, parms)
}

